FROM elasticsearch:2.4.6

RUN /usr/share/elasticsearch/bin/plugin install --batch analysis-icu
RUN /usr/share/elasticsearch/bin/plugin install --batch analysis-kuromoji
RUN /usr/share/elasticsearch/bin/plugin install --batch analysis-smartcn
RUN /usr/share/elasticsearch/bin/plugin install --batch analysis-stempel
